[package]
name = "commit-rs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "cr"
path = "src/main.rs"

[dependencies]
color-eyre = "0.6.3"
dialoguer = { version = "0.11.0", features = ["editor", "fuzzy-select"] }
git2 = "0.18.3"
